### ISSUE TITLE
Webhook URL doesn't get updated automatically when Ngrok URL changes

### ISSUE THREAD

**Issue by joeyfreund** [Shopify/shopify-app-js#121]
# Issue summary

During development, the Ngrok URL might change from time to time.

We mostly handle it gracefully - In the CLI, developers can choose to have the URL updated automatically, and the CLI takes care of updating the allowed URLs in Partners. In other words, things just work 🎉 

There is one exception - webhooks.
When the Ngrok changes, we don't update the webhook URL, which results in webhook delivery failure.

Once a developer figures out the source of the problem, they can hack their way around to update the webhook URL (the easiest way is to call `shopify.api.webhooks.register({session: res.locals.shopify.session})` in the context of a response).

There's also a [post on the Community Forum describing this problem](https://community.shopify.com/c/shopify-apis-and-sdks/update-webhook-url/td-p/1750369).

## Expected behavior

Things should just work 🎉 
If the Ngrok URL changes, the webhook URL should be updated transparently under the hood.

## Actual behavior

Webhook delivery fails start failing as soon as the Ngrok URL changes.

## Steps to reproduce the problem

I'm not sure how to trigger a Ngrok URL change, but if you wait for long enough, it will happen on its own.

**Comment by nzahrir** [comment]
Hey @joeyfreund I know this is unrelated, but how did you configure your webhoooks I am having trouble. I tried adding another topic to the GDPRHandler from the template. Are these webhooks handled differently since their URL is configured in the app setup of shopify partner? Where are you adding the  shopify.api.webhooks.register({session: res.locals.shopify.session}) ? Would it be after the shopify.auth.callback(). Since the OAuth is completed and the access token has been granted? Thanks for taking the time to read this.
`app.get(shopify.config.auth.path, shopify.auth.begin());
app.get(
  shopify.config.auth.callbackPath,
  shopify.auth.callback(),
  shopify.redirectToShopifyOrAppRoot()
);`
`app.post(
  shopify.config.webhooks.path,
  shopify.processWebhooks({ webhookHandlers: GDPRWebhookHandlers })
);`

`export default {
  /**
   * Customers can request their data from a store owner. When this happens,
   * Shopify invokes this webhook.
   *
   * https://shopify.dev/docs/apps/webhooks/configuration/mandatory-webhooks#customers-data_request
   */
  CUSTOMERS_DATA_REQUEST: {
    deliveryMethod: DeliveryMethod.Http,
    callbackUrl: "/api/webhooks",
    callback: async (topic, shop, body, webhookId) => {
      const payload = JSON.parse(body);
      // Payload has the following shape:
      // {
      //   "shop_id": 954889,
      //   "shop_domain": "{shop}.myshopify.com",
      //   "orders_requested": [
      //     299938,
      //     280263,
      //     220458
      //   ],
      //   "customer": {
      //     "id": 191167,
      //     "email": "john@example.com",
      //     "phone": "555-625-1199"
      //   },
      //   "data_request": {
      //     "id": 9999
      //   }
      // }
    },
  },

  /**
   * Store owners can request that data is deleted on behalf of a customer. When
   * this happens, Shopify invokes this webhook.
   *
   * https://shopify.dev/docs/apps/webhooks/configuration/mandatory-webhooks#customers-redact
   */
  CUSTOMERS_REDACT: {
    deliveryMethod: DeliveryMethod.Http,
    callbackUrl: "/api/webhooks",
    callback: async (topic, shop, body, webhookId) => {
      const payload = JSON.parse(body);
      // Payload has the following shape:
      // {
      //   "shop_id": 954889,
      //   "shop_domain": "{shop}.myshopify.com",
      //   "customer": {
      //     "id": 191167,
      //     "email": "john@example.com",
      //     "phone": "555-625-1199"
      //   },
      //   "orders_to_redact": [
      //     299938,
      //     280263,
      //     220458
      //   ]
      // }
    },
  },

  /**
   * 48 hours after a store owner uninstalls your app, Shopify invokes this
   * webhook.
   *
   * https://shopify.dev/docs/apps/webhooks/configuration/mandatory-webhooks#shop-redact
   */
  SHOP_REDACT: {
    deliveryMethod: DeliveryMethod.Http,
    callbackUrl: "/api/webhooks",
    callback: async (topic, shop, body, webhookId) => {
      const payload = JSON.parse(body);
      // Payload has the following shape:
      // {
      //   "shop_id": 954889,
      //   "shop_domain": "{shop}.myshopify.com"
      // }
    },
  },

  PRODUCTS_CREATE: {
    deliveryMethod: DeliveryMethod.Http,
    callbackUrl: "/api/webhooks",
    callback: async (topic, shop, body, webhookId) => {
      const payload = JSON.parse(body);
      // Payload has the following shape:
      // {
      //   "shop_id": 954889,
      //   "shop_domain": "{shop}.myshopify.com"
      // }
    },
  },
};`

**Comment by Ftsooy** [comment]
> Hey @joeyfreund I know this is unrelated, but how did you configure your webhoooks I am having trouble. I tried adding another topic to the GDPRHandler from the template. Are these webhooks handled differently since their URL is configured in the app setup of shopify partner? Where are you adding the shopify.api.webhooks.register({session: res.locals.shopify.session}) ? Would it be after the `shopify.auth.callback().` Since the OAuth is completed and the access token has been granted? Thanks for taking the time to read this. `app.get(shopify.config.auth.path, shopify.auth.begin()); app.get( shopify.config.auth.callbackPath, shopify.auth.callback(), shopify.redirectToShopifyOrAppRoot() );` `app.post( shopify.config.webhooks.path, shopify.processWebhooks({ webhookHandlers: GDPRWebhookHandlers }) );`
> 
> `export default { /**
> 
> * Customers can request their data from a store owner. When this happens,
> * Shopify invokes this webhook.
> * https://shopify.dev/docs/apps/webhooks/configuration/mandatory-webhooks#customers-data_request
>   */
>   CUSTOMERS_DATA_REQUEST: {
>   deliveryMethod: DeliveryMethod.Http,
>   callbackUrl: "/api/webhooks",
>   callback: async (topic, shop, body, webhookId) => {
>   const payload = JSON.parse(body);
>   },
>   },
> 
> /**
> 
> * Store owners can request that data is deleted on behalf of a customer. When
> * this happens, Shopify invokes this webhook.
> * https://shopify.dev/docs/apps/webhooks/configuration/mandatory-webhooks#customers-redact
>   */
>   CUSTOMERS_REDACT: {
>   deliveryMethod: DeliveryMethod.Http,
>   callbackUrl: "/api/webhooks",
>   callback: async (topic, shop, body, webhookId) => {
>   const payload = JSON.parse(body);
>   },
>   },
> 
> /**
> 
> * 48 hours after a store owner uninstalls your app, Shopify invokes this
> * webhook.
> * https://shopify.dev/docs/apps/webhooks/configuration/mandatory-webhooks#shop-redact
>   */
>   SHOP_REDACT: {
>   deliveryMethod: DeliveryMethod.Http,
>   callbackUrl: "/api/webhooks",
>   callback: async (topic, shop, body, webhookId) => {
>   const payload = JSON.parse(body);
>   },
>   },
> 
> PRODUCTS_CREATE: { deliveryMethod: DeliveryMethod.Http, callbackUrl: "/api/webhooks", callback: async (topic, shop, body, webhookId) => { const payload = JSON.parse(body); }, }, };`

Hey nzahrir, curious if you ever managed to get an additional webhook registered like you're asking here? I'm also having the same issues...

**Comment by nzahrir** [comment]
@Ftsooy if you are using a public app the GDPR webhook need to be configured manually in the app settings. I don't think GDPR topics require you to submit a post request to Shopify which might explain why trying to include a products create webhook does not work?

**Comment by nzahrir** [comment]
shopify.api.webhooks.register({session: res.locals.shopify.session}) I think this function is the one that submit the post request to shopify with all the added handlers
`PRODUCTS_CREATE: 
{ deliveryMethod: DeliveryMethod.Http, 
callbackUrl: "/api/webhooks", 
callback: async (topic, shop, body, webhookId) => { const payload = JSON.parse(body); }, }, };`` <--- Handler Example
