### ISSUE TITLE
`pnpm dev` with new app redirects to 404 instead of install page

### ISSUE THREAD

**Issue by xegulon** [Shopify/shopify-app-js#362]
# Issue summary

- "@shopify/shopify-app-express": "2.2.0"
- Node version: v18.16.1
- Operating system: Fedora 38

I have a Shopify app that is based on the node/express template.

In development mode, I want to develop on a different app name than before, then I want to install the new app on my development store. But this does not work, and instead of redirecting me to the Install page, I have:

![image](https://github.com/Shopify/shopify-app-js/assets/74178038/4f6deb1b-60e2-4996-b24e-8fff8c6889eb)

Precision: all my dependencies are at their latest versions.

## Expected behavior

Redirect to the install page for the new app.

## Actual behavior

Redirects to 404.

## Steps to reproduce the problem

1. Run `pnpm dev --reset` at the root of the project on Linux
2. Use a new app to develop on
3. Press `p` when eveything is ready

**Comment by paulomarg** [comment]
When you run the `dev --reset` command, are you seeing some log lines about an app uninstalled webhook? The error you're seeing is because the local database the template uses (`database.sqlite`) will still think the app is installed, even though it hasn't actually been installed as far as Shopify can see.

There are 2 ways this could be fixed:
- The app uninstalled webhook reaches the app (which will make the template delete existing sessions for that shop)
- You can delete the sessions from the database (or the database itself)
