### ISSUE TITLE
Expose Shopify API in shopifyApp from shopify-app-remix

### ISSUE THREAD

**Issue by wooque** [Shopify/shopify-app-js#379]
## Overview

Currently API is only exposed through `app.authenticate.admin(request)` it would be nice if it could be accessed with `app.api` as well, like in `shopify-app-express`

**Comment by byrichardpowell** [comment]
Hi @wooque 👋 ,

Thanks for opening an issue.

Please could you help me understand your use case? E.g: Why do you need an API client without first calling authenticate?

For the time being, you might be able to instantiate an API client using `@shopify/shopify-api-js` ([docs here](https://github.com/Shopify/shopify-api-js/tree/main/docs/reference/clients).  But it should be noted that the client returned from the authenticate functions in shopify-app-remix are a little different.

**Comment by wooque** [comment]
Because I would like to access API outside of HTTP request, for example from background job, where there is no request to be used for authentication, but I have session from session storage.

**Comment by byrichardpowell** [comment]
Thanks, makes sense.

We are learning how people want to use the package, so your input is really valuable, thank you! 2 questions:

1. Would the background job be the same codebase as your Remix codebase, or something different? What service would you use for the background job?   Our prediction when developing `@shopify/shopify-app-remix` was that background jobs would not be a "Remix" thing, which leads me to question 2:
2. Could you instantiate an API client directly instead? ([see docs here](https://github.com/Shopify/shopify-api-js/tree/main/docs/reference/clients)).  This might actually be preferable, because the API client `@shopify/shopify-app-remix` returns is tuned differently to how a background job client would be tuned.

Thanks again for the input.

**Comment by wooque** [comment]
1. Ideally everything would be in the same codebase. Just starting an app, so not sure about service, app would be deployed on Vercel, Vercel has cron jobs, but probably some other service would be used as well.
2. Yeah sure. I want to keep code interacting with Shopify agnostic how/where it's accessed, so it can be accessed from HTTP request, cron/background job, and using API probably better way.

**Comment by byrichardpowell** [comment]
Perfect, thanks for the context @wooque 

Since you can achieve what you need using the API client directly, I'm going to close this issue.

Thanks so much for taking the time to open an issue and to provide so much context.

**Comment by joelvh** [comment]
@byrichardpowell our use case to access `app.api` (instead of instantiating our own instance) would be to reference session helpers and similar functions like `api.session.getOfflineId(shop)` or `api.session.getCurrentId(...)`.

We've run into a few other methods we'd want to access to "override" some behaviors around session management that we can't otherwise access.

**Comment by joelvh** [comment]
@byrichardpowell hey! Yeah, I'm aware of the API clients and am looking to access other aspects of what `shopifyApi(...)` instantiates (e.g. the session).

Maybe I am not fully aware of how to use the built-in session management, but here's some examples:

- Using online sessions, we want to get access to the offline token to store that in a database. We can hard-code the offline session ID since we know the naming convention, but ideally we'd use `api.session.getOfflineId` to avoid hard-coding it in our app.
- We are sometimes validating the `hmac` and want access to `api.utils` for that. Sometimes we want to validate the request, but not initiate OAuth.
- `api.logger` would be useful to tie into, but not a priority

We spent a lot of time digging around the internals to figure out what was going on with #451 and got a workaround going. At some point, we'd wanted to short-cut some of logic in `AuthStrategy`, which during that process we'd wanted access to `api` to debug or simplify some of the functionality baked in there.

Ultimately, it would have been a convenience for those reasons and the remaining items are not critical, but handy.

I can reply back here as I come across other (more compelling) use cases.

**Comment by joelvh** [comment]
BTW, slightly off-topic -- we didn't see anything built-in to prune old sessions. Is the intent for us to implement our own process for this? (The session storage API implies deleting was considered, but not documented how it should be used.)

Thanks!

**Comment by byrichardpowell** [comment]
Thanks so much for the context @joelvh . If you can endulge me a little I have some more questions. 

> Using online sessions, we want to get access to the offline token to store that in a database. We can hard-code the offline session ID since we know the naming convention, but ideally we'd use api.session.getOfflineId to avoid hard-coding it in our app.

Interesting, thanks!  When you use online tokens we save the online & offline token to the database as part of OAuth. When you call `const { admin, session } = await unauthenticated.admin("lorem")`, the session that you get back is the offline session.  That's totally not obvious and very indirect, but does that help your use case?

> We are sometimes validating the hmac and want access to api.utils for that. Sometimes we want to validate the request, but not initiate OAuth.

In what instances are you validating the hmac where calling either `authentictae.admin(request)` or `authenticate.webhook(request)` does not help you?

> We spent a lot of time digging around the internals to figure out what was going on with https://github.com/Shopify/shopify-app-js/issues/451 and got a workaround going. At some point, we'd wanted to short-cut some of logic in AuthStrategy, which during that process we'd wanted access to api to debug or simplify some of the functionality baked in there.

Yeah, I've just looked at #451 now and that's a nasty workflow that we aren't handling, but we should.  Thanks for reporting it, and sorry it's cost you some hassle.  We look at issues every monday, and I can imagine us prioritizing this then.

If this issue were fixed would the requirements above (the ones I've quoted) go away?

**Comment by joelvh** [comment]
@byrichardpowell the `unauthenticated.admin(...)` definitely solves that! That was not obvious to look at since we were aware of online/offline as a boolean argument to `authenticated.admin(...)` and generally aren't looking to do anything unauthenticated. But now I understand that "unauthenticated" here means the request isn't being authenticated, but we can still retrieve shop information based on the domain.

We are moving away from using `hmac` directly, so that isn't needed anymore.

As of now, it seems we don't have a need for exposing `api`. I'll keep you posted if we run into anything else.

Thank you for your diligence~

**Comment by byrichardpowell** [comment]
> @byrichardpowell Another use case (that maybe is supported) is how to check if there's currently an online session without redirecting to the OAuth flow?

We don't provide any API's for that right now, but you do have access to the session table yourself, so you could look it up and check yourself.  I'm not sure if the ergonomics are great for that though.  What's your use case please?  I had assumed that checking for a valid online token & redirecting are always linked.
