### ISSUE TITLE
[shopify-app-remix] Authenicating public request 401

### ISSUE THREAD

**Issue by huykon** [Shopify/shopify-app-js#409]
## Overview/summary

I'm following this guide to get shopify storefront data https://github.com/Shopify/shopify-app-js/tree/main/packages/shopify-app-remix#authenticating-public-requests, but my request is 401 now, I guess we need an authorization at header for request, what should I do now?

**Comment by TheRealFlyingCoder** [comment]
Hey, random question, but do your other Authenticate methods pass successfully?

I currently get 401 on everything but it's a new project

**Comment by huykon** [comment]
@TheRealFlyingCoder you have to using like this https://github.com/Shopify/shopify-api-js/issues/936#issuecomment-1679170519

**Comment by TheRealFlyingCoder** [comment]
> In the meantime, I know it's not ideal, but you can use that comment you linked to and create a `new shopifyAPI.clients.Storefront`.

I actually struggled to figure this one out yesterday, I gave up and installed a separate API package to pass the access token to so I could make requests separately to the Shopify app.

I'll check again today, but I feel like the reexported ShopifyApi was missing this functionality? 👀

**Comment by paulomarg** [comment]
Hey folks! We've released a new version of the package that provides the unauthenticated Storefront context. Here is how you can use it in the latest versions: https://shopify.dev/docs/api/shopify-app-remix/v1/unauthenticated/unauthenticated-storefront

Since I believe this addresses the original issue, I'm going to close this. Feel free to open a new one if you still have problems.
