### ISSUE TITLE
Billing loop for Shopify App Review Team

### ISSUE THREAD

**Issue by StefanoDiLegami** [Shopify/shopify-app-js#420]
# Issue summary

After I have submitted my app to the Shopify App Store, somehow the Shopify App Review Team gets in a billing redirect loop when I have this following code: 

app.jsx
```
export async function loader({ request }) {
  const { session } = await authenticate.admin(request);
  const shop = session.shop.replace(".myshopify.com", "");
  const { billing } = await authenticate.admin(request);
  const isTest = shop === "teststore" 

  await billing.require({
    plans: ["MONTHLY"],
    isTest: isTest,
    onFailure: async () =>
      billing.request({ plan: "MONTHLY", isTest: isTest }),
  })
```

shopify.server.ts
```
const shopify = shopifyApp({
  billing: {
    MONTHLY: {
      trialDays: 3,
      amount: 0.99,
      currencyCode: "USD",
      interval: BillingInterval.Every30Days,
    },
  }
  });
```

On all my different test stores, and paid stores, I don't have any issues. I think it is related to the special Shopify Staff stores. 

I also have a screencast from Shopify App Review Team that shows this issue.

- `@shopify/shopify-app-remix` package and version: 1.0.4
- Node version: v18.15.0
- Operating system: macOS

## Expected behavior

After first approved billing, don't redirect again to billing page.

## Actual behavior

It always loops again to the billing page, even after approved billing. (Only for Shopify App Review Team stores)

## Steps to reproduce the problem

1. Setup billing with provided code in the remix template.
1. Check if it works on Shopify App Review Team stores.

**Comment by paulomarg** [comment]
Hi, thank you for reporting this. I'll escalate it to the reviews team to see if we can figure out what is going wrong here.

**Comment by francisbeaudoin** [comment]
Hey @StefanoDiLegami, could you either provide the app name or the api key that was submitted for review? 

Thanks

**Comment by StefanoDiLegami** [comment]
> Hey @StefanoDiLegami, could you either provide the app name or the api key that was submitted for review?
> 
> Thanks

Sure, here is the Client ID of the app I submitted for review:
fc333fcc46d236cee3bc41f31a2a9ec4

**Comment by paulomarg** [comment]
I understand this was already investigated and resolved, so I'm closing the issue. Please let me know if that's not the case.

**Comment by StefanoDiLegami** [comment]
> I understand this was already investigated and resolved, so I'm closing the issue. Please let me know if that's not the case.

Not really, I just completed the Review without billing and aferwards enabled billing again because it works on normal stores.

Check this screencast of App Review Team. 

https://screenshot.click/18-10-55631-49002.webm

**Comment by is2ei** [comment]
@paulomarg 

I'm facing the same issue.

My loader is like this:
```jsx
export async function loader({ request }) {
  const { admin, billing } = await authenticate.admin(request);

  const response = await admin.graphql(
    `#graphql
      query {
        shop {
          plan {
            displayName
            partnerDevelopment
          }
        }
      }
    `
  )
  const shop = await response.json()

  await billing.require({
    plans: [PLAN.BASIC],
    // https://github.com/Shopify/shopify-api-js/blob/main/docs/reference/billing/check.md#istest
    // https://shopify.dev/docs/apps/billing/purchase-adjustments/free-trials.md#set-up-free-testing
    isTest: shop.data.shop.plan.partnerDevelopment,
    onFailure: async () => {
      return billing.request({
        plan: PLAN.BASIC,
        // https://github.com/Shopify/shopify-api-js/blob/main/docs/reference/billing/request.md#istest
        // https://shopify.dev/docs/apps/billing/purchase-adjustments/free-trials.md#set-up-free-testing
        isTest: shop.data.shop.plan.partnerDevelopment
      })
    }
  })

  return json({ apiKey: process.env.SHOPIFY_API_KEY });
}
```

An app review specialist in Shopify Apps team tells me that an error/loop occurred in her store but the installation works fine in my development stores.

> It's worth pointing out that isTest should be consistent between the require and request calls,

I think I configured it consistently but the issue hasn't been resolved.

---
Environment:
@shopify/shopify-app-remix package and version: 1.1.0
Node version: v18.x.x
Operating system: I'm not sure which OS the app review specialist uses.

**Comment by gerardkabre** [comment]
@AlexHooperDev @is2ei Did you manage to sort it out? I think the `isTest` param sent to the billing API must be kept to true even if being production to allow them to review and test without real payments, and remove once it is listed.

**Comment by is2ei** [comment]
@gerardkabre 

> Did you manage to sort it out?

No, but I communicated with the review team and published my app successfully.

> Having the same issue I think the isTest param sent to the billing API must be kept to true even if being production to allow them to review and test without real payments, and change it back to false once listed

I'm not sure it is the right way to do that. Is there any documentation that mention it?

**Comment by paulomarg** [comment]
Hey folks, thank you for your feedback, and sorry for the delayed response. The team is looking into the issue, and I've reiterated the issue.

Thank you for your patience while we try to resolve this!

**Comment by paulomarg** [comment]
I was working with the teams to find a solution, and it seems like @MathiasGr was correct in that it is related to the staff stores used by the app review team - we're looking into a way to automatically handle these cases in the future, if we can.

However, [as per our documentation](https://shopify.dev/docs/apps/store/review/app-pre-submission#test-your-app-s-billing-system), devs should actually turn off real purchases when submitting their apps for review, which should also prevent this problem from happening. You can re-enable real purchases after the approval comes through. We've also connected with the app review team to flag that if they run into this case in the future.

I apologize for not mentioning this before, but I hadn't made the connection between staff stores and how they affect billing as the root cause here.

**Comment by tommypepsi** [comment]
@paulomarg I think this should be reopened. It just happened to us in production on a shopify plus store. There was "sandbox" in the myshopify url name, but it was an actual store. I believe that somehow shopify turned something on for them that forces all recurring charges to be in test mode. 

using the query:
```graphql
{
  shop {
    plan {
      partnerDevelopment
    }
  }
}
```
was false and the plan name was simply "Shopify Plus". I'm guessing shopify review stores have something similar enabled.

What happens is that if we use the logic `isTest: shop.data.shop.plan.partnerDevelopment`, for these kind of store we are looking for a recurring charge that is not test mode, but then the configuration of the store forces the charge to be test mode. So this causes an infinite loop of trying to find a charge that is not in test mode.

This issue is not really caused by this library, more the fact that shopify lacks any API to recognize these particular stores that have this weird flag that forces the charges to be test mode. 

@paulomarg if you have any say in this, I believe that whatever flag is turned on on the review stores or this particular store I got in production, should turn the "partnerDevelopment" variable to true. Or maybe another separate property if this is too complex or doesn't make sense since they are not actual development stores.

For now we added a whitelist in our code since this doesn't seem too common, but this is not really a perfect solution as I imagine this flag could be turned off anytime by shopify.

**Comment by paulomarg** [comment]
Hey @tommypepsi , thanks for that. I believe you're right - we can't fully trust `partnerDevelopment` because not all "non-real" stores will have that flag set. I've raised that point with the team, and they're looking into it, but I'll reiterate so that we can improve this flow!

**Comment by dani-sanomads** [comment]
Do we have any updates on this , @paulomarg ? Still facing this issue for remix app after the billing approval it redirects again.

**Comment by MathiasGr** [comment]
Yes... this is still a blocking issue 1 year after the initial report... crazy. And now the support team is saying there is not issue anymore while nothing has changed.

**Comment by paulomarg** [comment]
Hey folks, I'm sorry this is still an issue. We've been working with the teams on this, and we currently have 2 recommendations to work around this issue:
- Use the new [Shopify managed pricing](https://shopify.dev/docs/apps/launch/billing/managed-pricing), which enables you to define how to charge stores while publishing your app, so you don't have to use the billing API at all to set them up.
  - Currently, the `check` method won't work without a config for the app, but I have a WIP PR to address that: #1236. So until that's released, you would need to manually write the GraphQL query to look for purchases in a multi-plan scenario.
- Always use test purchases for the app review process - you can update it to use real purchases after the review process

**Comment by jagthedrummer** [comment]
@paulomarg Regarding this advice:

> Always use test purchases for the app review process - you can update it to use real purchases after the review process

We have an app that is published in the app store. For some reason your team has decided to re-review it and they're stuck in this billing loop. If we follow your recommendation to make the re-review app happy we're breaking subscriptions for regular shops. This issue has been open for nearly two years. When can we expect a proper fix? It's a major problem that the shops that Shopify uses for app review behave differently than normal shops or even development shops. Why do you have a secret third kind of shop that doesn't represent real-world conditions?
