### ISSUE TITLE
Billing API access in proxy requests

### ISSUE THREAD

**Issue by rkbhochalya** [Shopify/shopify-app-js#469]
I'm working on an app that handles proxy requests from the shop frontend. The `authenticate.public.appProxy` function is very handy in validating these requests.

However, I need access to the billing API in order to set a limit on the number of such requests based on the active plan. Ideally, `UnauthenticatedAdminContext` could provide this access. This would be beneficial, particularly for cases where I'm not handling an admin request from Shopify, such as in listing shops with their current plan in an internal dashboard.

Alternatively, having the ability to access the [`shopifyApi`](https://www.npmjs.com/package/@shopify/shopify-api) interface from the remix app would also be acceptable.

Any workarounds for this issue would be greatly appreciated.

**Comment by byrichardpowell** [comment]
Hey @rkbhochalya 👋 

Thanks for opening an issue, and sorry we are missing this functionality.

Please could you explain your use case?  2 questions to help me understand:

1. I assume that you need `billing.require()`, but because this is a request from the storefront, you could not use `billing.cancel()` or `billing.request()`?
2. What would you do if the shop does not have the correct billing setup?  Would that be a 401 response?

I _think_ we could add something here, but I need to look into it. E.g:

```
const {billing} = authenticate.public.appProxy(request)

await billing.require({
  plans: ["MONTHLY_PLAN"],
  isTest: true,
  onFailure: async () => throw new Response(401) ,
});
```

Would this work?

In the meantime, so you are unblocked, you can you the admin GraphQL API to perform the same check yourself. This is the query that the  Remix template uses under the hood:

```
  query appSubscription($endCursor: String) {
    currentAppInstallation {
      activeSubscriptions {
        id
        name
        test
      }

      oneTimePurchases(first: 250, sortKey: CREATED_AT, after: $endCursor) {
        edges {
          node {
            id
            name
            test
            status
          }
        }
        pageInfo {
          hasNextPage
          endCursor
        }
      }
    }
  }
```

Just to set expectations, since there is a workaround and we haven't got many requests for this, it might be a while until we get to this.

**Comment by sanjaymakwana05** [comment]
Hi @tomoyanakano  @byrichardpowell 

I hope you're doing well!

I'm currently integrating Shopify's billing API into my Remix app and using billing.check() to verify the current plan. However, I couldn't find a way to retrieve the number of remaining trial days from this function.

Here’s a simplified example of what I’m doing:


`const plan = await billing.check({ 
  plans: ["basic", "pro", "premium"]
});
console.log(plan);`

The response contains details about the current plan but doesn’t seem to include trial-related information. Is there any way to get the trial days remaining using billing.check()? Or should I query a different API endpoint for this data?

Any guidance would be greatly appreciated. Thanks in advance!
