### ISSUE TITLE
Billing is requested in some stores in a test state.

### ISSUE THREAD

**Issue by maneko00** [Shopify/shopify-app-js#574]
# Issue summary
App billing is only requested in some stores in a test state. I believe this is a bug. 
Please let me know the solution.

The store plans requested in the test condition were Custom and Shopify Plus. 
However, the majority of stores on the same plans do not have billing requested in the test condition.

- `@shopify/shopify-app-remix` package and version:1.3.0
- Operating system: Mac
shopify.server.js
```.js
export const MONTHLY_PLAN = 'Basic';
const shopify = shopifyApp({
  billing: {
    [MONTHLY_PLAN]: {
      amount: 3.49,
      currencyCode: 'USD',
      interval: BillingInterval.Every30Days,
      trialDays: 7
    },
  },
});
```
routes/app.jsx
```.jsx
import { MONTHLY_PLAN, authenticate } from "~/shopify.server";
export async function loader({ request }) {
  const { billing } = await authenticate.admin(request);
  await billing.require({
    plans: [MONTHLY_PLAN],
    isTest: false,
    onFailure: async () => billing.request({
      plan: MONTHLY_PLAN,
      isTest: false,
    }),
  });
}
```

**Comment by paulomarg** [comment]
Hi, thanks for raising this. Based on the code samples, it seems to me like your app should be requesting non-test payments for every store, so I'm surprised to see the difference in behaviour.

A few questions:
- is it possible that you have a different `loader` or `action` that's setting the flag to `true`?
- have you changed this code after you started making "real" payment requests?
- could the test charges be from before you switched on real payments? E.g. if you transferred a development store?

Unfortunately, it's difficult for me to tell what's going wrong here just based on the code. If you're able to get a set of steps to reliably reproduce this, we can fix it if it's a bug, but otherwise you could try contacting support to see if they can help identify the issue based on the affected stores.

**Comment by maneko00** [comment]
Thank you for your response.

- is it possible that you have a different loader or action that's setting the flag to true?
->  No, the flag is fixed to false.
- have you changed this code after you started making "real" payment requests?
-> Yes I have.
- could the test charges be from before you switched on real payments? E.g. if you transferred a development store?
-> I do not know how to check about it.

I will try contacting support to see if they can help identify the issue based on the affected stores.

**Comment by maneko00** [comment]
I contacted support and they were able to identify the problem with the store in question.

> We have found that the store is connected to a Shopify staff test shop. This would automatically create testing billing plans, usually intended for app troubleshooting on staff test shops, so that's why you are seeing the issue pop up there.

**Comment by paulomarg** [comment]
Hey, I think you're spot on - staff stores might be the problem here. We're investigating the ideal way of detecting that scenario so we can forcibly accept test purchases in that case. Thanks for the info folks, this was super helpful!

**Comment by maneko00** [comment]
@paulomarg 
Sorry I missed that.
Could you please explain in a different way because I can't understand the question?

**Comment by maneko00** [comment]
@paulomarg 
Is there any progress?
My app is being asked by Shopify to fix this issue.
