### ISSUE TITLE
Expose `ping` method for `@shopify/shopify-app-session-storage-redis`

### ISSUE THREAD

**Issue by kibertoad** [Shopify/shopify-app-js#724]
## Overview

Since Redis client for `@shopify/shopify-app-session-storage-redis` is private, there is no easy and cheap way to perform a healthcheck for the Redis connectivity of it.

It would be great if there was a `ping()` method exposed, which would invoke `ping()` on a client and return an object of this structure:

```js
{
  isSuccessful: boolean
  error?: Error
}
```

**Comment by kibertoad** [comment]
If there is approval for this request, we can provide a PR for it

**Comment by paulomarg** [comment]
That sounds like a good idea to me. Another option that might also work and that would give apps more freedom would be the ability to pass in a client like:

```ts
import {createClient} from 'redis';
import {RedisSessionStorage} from '@shopify/shopify-app-session-storage-redis';

const client = createClient( ... );
const storage = new RedisSessionStorage(client, { ... });
```

Since we only use the `dbUrl` parameter to create a new client ourselves. That way you can do whatever you need to with the client without having to go through the package.

Which do you think would work better here?

**Comment by kibertoad** [comment]
@paulomarg Sure, we'll pick it up. Thank you for the reply!

**Comment by kibertoad** [comment]
We are still planning to work on it
