### ISSUE TITLE
Can't import `enum` from generated GraphQL type definition files

### ISSUE THREAD

**Issue by vincaslt** [Shopify/shopify-app-js#765]
The GraphQL type definitions are generated into `admin.types.d.ts` file as per: https://github.com/Shopify/shopify-api-js/blob/3e55838fe4f192d5d639670834f2a002800ba271/packages/api-codegen-preset/src/helpers/api-configs.ts#L24

The problem I'm facing is that I can't import `enum` from the generated file - .d.ts files are discarded during compilation.

So this import won't work:

```
import { ImageContentType } from "~/types/admin.types";
```

`[ERROR] Could not resolve "~/types/admin.types"`:
![image](https://github.com/Shopify/shopify-api-js/assets/944727/c9292e66-8d38-496b-add7-592de0c511b7)

Am I maybe wrong to try to import stuff from those files and they should be used somehow differently?

**Comment by aborchew** [comment]
Just want to give @kusyka911 a shoutout here - thanks! 🙏🏻

**Comment by rlj1202** [comment]
Because the `admin.generated.ts` file imports the `admin.types.ts` file as follows, TypeScript files are not compiled.

```ts
import * as AdminTypes from './admin.types.ts';
```

```
error TS5097: An import path can only end with a '.ts' extension when 'allowImportingTsExtensions' is enabled.
```

The error log says the `allowImportingTsExtensions` option must be enabled. To enable the option, either `--noEmit` or `--emitDeclarationOnly` must be set also. Then I cannot make source codes to be running in production. File extension must be omitted in generated file!
