### ISSUE TITLE
sameSite: Lax is failing to set the cookie

### ISSUE THREAD

**Issue by IonicaBizau** [Shopify/shopify-app-js#777]
# Issue summary

Because [`sameSite: lax`](https://github.com/Shopify/shopify-api-js/blob/6b7bd64bc4f311b1fe3c7c4075d548eee3c7cd94/lib/auth/oauth/oauth.ts#L70), the cookies are not being set by the oauth being call.

## Expected behavior
It should set the cookies and authenticate the embedded app.

We manually changed these lines in oauth.js into [`sameSite: "none"`](https://github.com/Shopify/shopify-api-js/blob/6b7bd64bc4f311b1fe3c7c4075d548eee3c7cd94/lib/auth/oauth/oauth.ts#L70) and it works, but being a change done in `node_modules` it will not work long term.

Is there any way to set the sameSite policy or another way to solve this issue?

**Comment by FranciscoBejaranoBluEdgeUsa** [comment]
This issue is still happening, it is happening in one of our custom apps and no matter what we try (even going into the npm package and editing it to "sameSite: 'none'") we can't solve it.

Any suggestions?

**Comment by Ydoug36** [comment]
Duplicate of #1460

**Comment by lizkenyon** [comment]
Hi folks 👋 

It seems like there are several different problems reported here. 

The original issue seems to be the requirement of a domain wide cookie for some OAuth flows when you redirect to a different domain to finish. This [PR](https://github.com/Shopify/shopify-api-js/pull/905) was started to resolve this issue but it was never completed. 

Because Token Exchange is our new recommended approach for authorization, the Shopify team won't be taking on this feature request at the current time.

If this issue is still affecting your app, and you would like to port that PR to our new repo, the Shopify team would have capacity to review it. Thanks
